Add OpenJDK dependency required for "jni.h"
Fixes docker build: Solves

```
100%] Linking CXX executable ../tests/model_test
[100%] Built target model_test
/code/jni/kenlm_wrap.cc:28:17: fatal error: jni.h: No such file or directory
 #include <jni.h>
                 ^
compilation terminated.
Removing intermediate container 0c2cb0c17a12

```